name: ARM Workflow

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and test
      run: |
        echo "Running on ${{ matrix.architecture }}"
    - name: build
      run: |
        sudo apt -y install build-essential cmake libboost-system-dev libboost-program-options-dev libssl-dev default-libmysqlclient-dev -yqq
        pwd;ls
        # cd trojan/
        # mkdir build
        # cd build/
        # cmake ..
        # make
        # ctest
        # sudo make install
